# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[1404-amd64]
	distro = "ubuntu"
	description = "ubuntu LTS 1404 amd64 vagrant build"
	arch = "amd64"
	image = "server"
	release = "14.04"
	builder_types = [
		"virtualbox-iso"
	]
	[1404-amd64.builders]
		[4204-amd64.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
		[1404-amd64.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"memory=4096"
			]
[centos7_x86_64]
	distro = "centos"
	description = "centos 7 x86_64 build"
	arch = "x86_64"
	image = "minimal"
	release = "7"
	builder_types = [
		"virtualbox-iso"
	]
	[centos7_x86_64.builders]
		[centos7_x86_64.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[centos7_x86_64.builders.virtualbox-iso.arrays]
				vboxmanage = [
					"--memory=4096"
				]
	
[jessie_amd64]
	distro = "debian"
	description = "debian jessie build"
	arch = "amd64"
	image = "netinst"
	release = "8"
	builder_types = [
		"virtualbox-iso"
	]
	[jessie_amd64.builders]
		[jessie_amd64.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
		[jessie_amd64.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"--memory=4096"
			]
		
[1404-salt]
	distro = "ubuntu"
	description = "ubuntu LTS 1404 amd64 server build, minimal salt install"
	arch = "amd64"
	image = "server"
	release = "14.04"
	builder_types = [
		"virtualbox-iso"
	]
	provisioner_types = [
		"salt-masterless"
	]
	[1404-salt.builders]
		[1404-salt.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[1404-salt.builders.virtualbox-iso.arrays]
				vboxmanage = [
					"--memory=4096"
				]
	[1404-salt.provisioners]
		[1404-salt.provisioners.salt-masterless]
			settings = [
				"local_state_tree = salt-masterless/salt",
				"local_pillar_roots = salt-masterless/pillar",
				"minion_config = salt-masterless/"
			]

[1404-go]
	distro = "ubuntu"
	description = "ubuntu LTS 1404 amd64 desktop build, minimal install w go"
	arch = "amd64"
	release = "14.04"
	image = "server"
	builder_types = [
		"virtualbox-iso"
	]
	post_processor_types = [
		"vagrant"
	]
	provisioner_types = [
		"shell"
	]
	[1404-go.builders]
		[1404-go.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"--memory=4096"
			]
	[1404-go.post_processors]
		[1404-go.post_processors.vagrant]
			[1404-go.post_processors.vagrant.arrays]
				only = [
					"virtualbox-iso"
				]
	[1404-go.provisioners]
		[1404-go.provisioners.shell]
			[1404-go.provisioners.shell.arrays]
				only = [
					"virtualbox-iso"
				]
				scripts = [ 
					"setup.sh",
					"sudoers.sh",
					"vagrant.sh",
					"customize.sh",
					"cleanup.sh",
				]
