# These templates generate examples for all supported Packer components with
# only the required settings, with a few exceptions. The result of each named
# template is a Packer template with all Packer components that Feedlot
# supports and only the settings that are required by Packer.
[1604-64-required]
distro = "ubuntu",
description = "Ubuntu 1604 LTS amd64 build with all supported components; required settings only",
arch = "amd64",
image = "server",
release = "16.04",
builder_types = [
	"amazon-chroot",
	"amazon-ebs",
	"amazon-instance",
	"digitalocean",
	"googlecompute",
	"null",
	"virtualbox-iso",
	"virtualbox-ovf",
	"vmware-iso",
	"vmware-vmx"
],
post_processor_types = [
	"compress",
	"docker-import",
	"docker-tag",
	"docker-push",
	"docker-save",
	"docker-tag",
	"vagrant",
	"vagrant-cloud",
	"vsphere"
],
provisioner_types = [
	"ansible-local",
	"chef-client",
	"chef-solo",
	"file",
	"puppet-masterless",
	"puppet-server",
	"salt-masterless",
	"shell"
]

[centos6-64-required]
distro = "centos",
description = "CentOS 6 x86_64 build with all supported components; required settings only",
arch = "x86_64",
image = "minimal",
release = "6",
builder_types = [
	"amazon-chroot",
	"amazon-ebs",
	"amazon-instance",
	"digitalocean",
	"googlecompute",
	"null",
	"virtualbox-iso",
	"virtualbox-ovf",
	"vmware-iso",
	"vmware-vmx"
],
post_processor_types = [
	"compress",
	"docker-import",
	"docker-tag",
	"docker-push",
	"docker-save",
	"docker-tag",
	"vagrant",
	"vagrant-cloud",
	"vsphere"
],
provisioner_types = [
	"ansible-local",
	"chef-client",
	"chef-solo",
	"file",
	"puppet-masterless",
	"puppet-server",
	"salt-masterless",
	"shell"
]

[centos7-64-required]
distro = "centos",
description = "CentOS 7 x86_64 build with all supported components; required settings only",
arch = "x86_64",
image = "minimal",
release = "7",
builder_types = [
	"amazon-chroot",
	"amazon-ebs",
	"amazon-instance",
	"digitalocean",
	"googlecompute",
	"null",
	"virtualbox-iso",
	"virtualbox-ovf",
	"vmware-iso",
	"vmware-vmx"
],
post_processor_types = [
	"compress",
	"docker-import",
	"docker-tag",
	"docker-push",
	"docker-save",
	"docker-tag",
	"vagrant",
	"vagrant-cloud",
	"vsphere"
],
provisioner_types = [
	"ansible-local",
	"chef-client",
	"chef-solo",
	"file",
	"puppet-masterless",
	"puppet-server",
	"salt-masterless",
	"shell"
]

[jessie-64-required]
distro = "debian",
description = "Debian Jessie build with all supported components; required settings only",
arch = "amd64",
image = "netinst",
release = "8",
builder_types = [
	"amazon-chroot",
	"amazon-ebs",
	"amazon-instance",
	"digitalocean",
	"googlecompute",
	"null",
	"virtualbox-iso",
	"virtualbox-ovf",
	"vmware-iso",
	"vmware-vmx"
],
post_processor_types = [
	"compress",
	"docker-import",
	"docker-tag",
	"docker-push",
	"docker-save",
	"docker-tag",
	"vagrant",
	"vagrant-cloud",
	"vsphere"
],
provisioner_types = [
	"ansible-local",
	"chef-client",
	"chef-solo",
	"file",
	"puppet-masterless",
	"puppet-server",
	"salt-masterless",
	"shell"
]
