# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
distro = "ubuntu"
description = "ubuntu LTS 1404 amd64 vagrant build"
arch = "amd64"
image = "server"
release = "14.04"
builder_types = [
	"virtualbox-iso"
]
	[1404-64.provisioners.shell.arrays]
	scripts = [
		"setup",
		"sudoers",
		"vagrant",
		"vbox",
		"cleanup"
	]

[centos6-64]
distro = "centos"
description = "centos 6 x86_64 vagrant build"
arch = "x86_64"
image = "Minimal"
release = "6"
builder_types = [
	"virtualbox-iso"
]
	[centos6-64.provisioners.shell.arrays]
	scripts = [
		"setup",
		"sudoers",
		"vagrant",
		"vbox",
		"cleanup"
	]

[centos7-64]
distro = "centos"
description = "centos 7 x86_64 vagrant build"
arch = "x86_64"
image = "Minimal"
release = "7"
builder_types = [
	"virtualbox-iso"
]
	[centos7-64.provisioners.shell.arrays]
	scripts = [
		"setup",
		"sudoers",
		"vagrant",
		"vbox",
		"cleanup"
	]

[jessie-64]
distro = "debian"
description = "debian jessie amd64 vagrant build"
arch = "amd64"
image = "netinst"
release = "8"
builder_types = [
	"virtualbox-iso"
]
	[jessie-64.provisioners.shell.arrays]
	scripts = [
		"setup",
		"sudoers",
		"vagrant",
		"vbox",
		"cleanup"
	]
