## rancher.toml contains default values for the application ENV varaiables. 
## Rancher only uses these values if their respective ENV variables do not
## exist or are not set. To use custom settings, set the respective ENV
## variables prior to running.
##
## Rancher's ENV variable names are the same as their respective config names
## except they are prefixed with 'rancher_'; e.g. the 'default_file' setting's
## environment variable name is 'rancher_default_file'.

## Configuration files.
default_file      = "conf/default.toml"
supported_file    = "conf/supported.toml"
build_file        = "conf.d/build.toml"
build_list_file   = "conf.d/build_list.toml"

## Logging
log                = true
log_file       = "rancher.log"
log_level_file     = "INFO"
log_level_stdout   = "TRACE"

## Misc. 
# The delimiter that signifies the start of a Rancher parameter. This Parameter
# will be dynamically replaced at build time.
param_delim_start  = ":"

