## rancher.toml contains default values for the application ENV varaiables. 
## Rancher only uses these values if their respective ENV variables do not exist
## or are not set. To use custom settings, set the respective ENV variables 
## prior to running.

## Configuration files.
defaults_file           = "conf/defaults.toml"
supported_file          = "conf/supported.toml"
builds_file             = "conf.d/builds.toml"
build_lists_file        = "conf.d/build_lists.toml"

## Logging
log_to_file		= true
log_filename		= "rancher.log"
log_level_file		= "INFO"
log_level_stdout	= "TRACE"

## Misc. 
# The delimiter that signifies the start of a Rancher parameter. This Parameter
# will be dynamically replaced at build time.
param_delim_start		= ":"

