# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[1404-64-vbox-vagrant]
distro = "ubuntu"
description = "ubuntu LTS 1404 amd64 virtualbox vagrant build"
arch = "amd64"
image = "server"
release = "14.04"
builder_types = [
	"virtualbox-iso"
]
[1404-64-vbox-vagrant.provisioners]
	[1404-64-vbox-vagrant.provisioners.shell]
		[1404-64-vbox-vagrant.provisioners.shell.arrays]
		scripts = [ 
			"setup",
			"vagrant",
			"sudoers",
			"vbox",
			"cleanup",
		]

[centos6-64-vbox-vagrant]
distro = "centos"
description = "centos 6 x86_64 virtualbox vagrant build"
arch = "x86_64"
image = "Minimal"
release = "6"
builder_types = [
	"virtualbox-iso"
]
[centos6-64-vbox-vagrant.provisioners]
	[centos6-64-vbox-vagrant.provisioners.shell]
		[centos6-64-vbox-vagrant.provisioners.shell.arrays]
		scripts = [ 
			"setup",
			"vagrant",
			"sudoers",
			"vbox",
			"cleanup",
		]

[centos7-64-vbox-vagrant]
distro = "centos"
description = "centos 7 x86_64 vagrant build"
arch = "x86_64"
image = "Minimal"
release = "7"
builder_types = [
	"virtualbox-iso"
]
[centos7-64-vbox-vagrant.provisioners]
	[centos7-64-vbox-vagrant.provisioners.shell]
		[centos7-64-vbox-vagrant.provisioners.shell.arrays]
		scripts = [ 
			"setup",
			"vagrant",
			"sudoers",
			"vbox",
			"cleanup",
		]

[jessie-64-vbox-vagrant]
distro = "debian"
description = "debian jessie amd64 virtualbox vagrant build"
arch = "amd64"
image = "netinst"
release = "8"
builder_types = [
	"virtualbox-iso"
]
[jessie-64-vbox-vagrant.provisioners]
	[jessie-64-vbox-vagrant.provisioners.shell]
		[jessie-64-vbox-vagrant.provisioners.shell.arrays]
		scripts = [ 
			"setup",
			"vagrant",
			"sudoers",
			"vbox",
			"cleanup",
		]
