# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[1404-64]
	distro = "ubuntu"
	description = "ubuntu LTS 1404 amd64 vagrant build"
	arch = "amd64"
	image = "server"
	release = "14.04"
	builder_types = [
		"virtualbox-iso"
	]
	[1404_amd64.builders]
		[1404_amd64.builders.common]
			settings = [
				"ssh_wait_timeout = 30m"
			]
		[1404_amd64.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"memory=4096"
			]
[centos7-64]
	distro = "centos"
	description = "centos 7 x86_64 vagrant build"
	arch = "x86_64"
	image = "minimal"
	release = "7"
	builder_types = [
		"virtualbox-iso"
	]
	[centos7_x86_64.builders]
		[centos7_x86_64.builders.common]
			settings = [
				"ssh_wait_timeout = 30m"
			]
			[centos7_x86_64.builders.virtualbox-iso.arrays]
				vboxmanage = [
					"--memory=4096"
				]
	
[jessie-64]
	distro = "debian"
	description = "debian jessie amd64 vagrant build"
	arch = "amd64"
	image = "netinst"
	release = "8"
	builder_types = [
		"virtualbox-iso"
	]
	[jessie_amd64.builders]
		[jessie_amd64.builders.common]
			settings = [
				"ssh_wait_timeout = 30m"
			]
		[jessie_amd64.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"--memory=4096"
			]
