# Default builder variable settings for Rancher. Merging the contents of this
# file with supported.toml provids the default settings for each distro.
description = "Default Rancher template"
name = ":build_name"
commands_src_dir = ":src_dir/commands"
http_dir = "http"
http_src_dir = ":src_dir/:http_dir"
out_dir = "out/:type/:build_name"
src_dir = "src/:type"
scripts_dir = "scripts"
scripts_src_dir = ":src_dir/:scripts_dir"
min_packer_version = "0.4.0"
builder_types = [
    "virtualbox-iso",
    "vmware-iso"
]
post_processor_types = [
	"vagrant"
]
provisioner_types = [
	"shell"
]
[builders]
	[builders.common]
	settings = [	
		"boot_command = :commands_src_dir/boot.command",
		"boot_wait = 5s",
		"disk_size = 20000",
		"headless = true",
		"http_directory = :http_dir",
		"iso_checksum_type = sha256",
		"shutdown_command = :commands_src_dir/shutdown.command",
		"ssh_password = vagrant",
		"ssh_port = 22",
		"ssh_username = vagrant",
		"ssh_wait_timeout = 240m",
		"vm_name = :build_name",
	]
	[builders.virtualbox-iso]
	settings = [
		"guest_os_type = ",
		"guest_additions_pat = VBoxGuestAdditions_{{ .Version }}.iso",
		"virtualbox_version_file = .vbox_version"
	]
		[builders.virtualbox-iso.arrays]
		vm_settings = [
			"cpus=1",
			"memory=1024"	
		]
	[builders.vmware-iso]
	settings = [
		"guest_os_type = ",
		"tools_upload_flavor = linux"
	]
		[builders.vmware-iso.arrays]
		vm_settings = [
			"cpuid.coresPerSocket=1",
			"memsize=1024",
			"numvcpus=1"
		]
[post_processors]
	[post_processors.vagrant]
	settings = [
		"compression_level = 9",
		"keep_input_artifact = false",
		"output =  :out_dir/box/:build_name.box"
	]
		[post_processors.vagrant.arrays]
		only = [
			"virtualbox.iso"
		]
[provisioners]
	[provisioners.shell]
	settings = [
		"execute_command = :commands_src_dir/execute.command"
	]
		[provisioners.shell.arrays]
		scripts = [ 
			":scripts_dir/setup.sh",
			":scripts_dir/vagrant.sh",
			":scripts_dir/sudoers.sh",
			":scripts_dir/cleanup.sh",
		]

