# Default builder variable settings for Rancher. Merging the contents of this
# file with supported.toml provids the default settings for each distro.
description = "Default Rancher template"
name = ":build_name"
#http_dir = "http"
#command_dir = "commands"
out_dir = "out/:build_name"
src_dir = "src"
min_packer_version = "0.4.0"
builder_types = [
    "virtualbox-iso",
]
post_processor_types = [
	"vagrant"
]
provisioner_types = [
	"shell-scripts"
]
[builders]
	[builders.common]
		settings = [	
			"boot_command = :commands_src_dir/boot.command",
			"boot_wait = 5s",
			"disk_size = 20000",
			"headless = true",
			"http_directory = :http_dir",
			"iso_checksum_type = sha256",
			"shutdown_command = :commands_src_dir/shutdown.command",
			"ssh_password = vagrant",
			"ssh_port = 22",
			"ssh_username = vagrant",
			"ssh_wait_timeout = 240m",
			"vm_name = :build_name",
		]
	[builders.virtualbox-iso]
		settings = [
			"guest_os_type = ",
			"guest_additions_path = VBoxGuestAdditions_{{ .Version }}.iso",
			"virtualbox_version_file = .vbox_version"
		]
		[builders.virtualbox-iso.arrays]
			vboxmanage = [
				"cpus=1",
				"memory=1024"	
			]
[post_processors]
	[post_processors.vagrant]
		settings = [
			"compression_level = 9",
			"keep_input_artifact = false",
			"output =  :out_dir/box/:build_name.box"
		]
		[post_processors.vagrant.arrays]
			only = [
				"virtualbox.iso"
			]
[provisioners]
	[provisioners.shell]
		settings = [
			"execute_command = :commands_src_dir/execute.command"
		]
		[provisioners.shell-scripts.arrays]
			scripts = [ 
				":scripts_dir/setup.sh",
				":scripts_dir/vagrant.sh",
				":scripts_dir/sudoers.sh",
				":scripts_dir/cleanup.sh",
			]

