# Default builder variable settings for Rancher. Merging the contents of this
# file with supported.toml provids the default settings for each distro.
#
# By default, the VMWare-iso and Virtualbox-iso builders are supported. If
# you want the default templates to support only one, remove the other one from
# the 'builder_type' section. If you wish to support something else, By
# default, you will need to remove the builder types that you do not want to
# support and add the builder type(s) that you do wish to support along with
# the relevant builder settings.
#
# Only the Packer sections enumerated in the {packer-section}_type sections
# are used by Rancher, any other sections defined within a template are ignored
# during the Packer template build process.
#
# Most customizations should probably be done in rancher build templates, but
# any settings that are going to be fairly consistent across builds should
# probably be put in here; minimizing the things that need to be set in a 
# specific build template.
description = "Default Rancher template"
name = ":build_name"
out_dir = "out/:build_name"
src_dir = "src"
include_component_string = "true"
min_packer_version = "0.5.0"
builder_types = [
    "virtualbox-iso",
	"vmware-iso",
]
[builders]
	[builders.common]
		settings = [	
			"boot_command = boot.command",
			"boot_wait = 5s",
			"disk_size = 20000",
			"headless = true",
			"http_directory = http",
			"iso_checksum_type = sha256",
			"output_directory = :out_dir",		
			"shutdown_command = shutdown.command",
			"ssh_password = vagrant",
			"ssh_port = 22",
			"ssh_username = vagrant",
			"ssh_wait_timeout = 240m",
			"vm_name = :build_name",
		]
	[builders.virtualbox-iso]
		settings = [
			"guest_additions_path = VBoxGuestAdditions_{{ .Version }}.iso",
			"virtualbox_version_file = .vbox_version"
		]
		[builders.virtualbox-iso.arrays]
			vboxmanage = [
				"cpus=1",
				"memory=1024"	
			]
	[builders.vmware-iso]
		settings = [
			"guest_additions_path = VBoxGuestAdditions_{{ .Version }}.iso",
			"virtualbox_version_file = .vbox_version"
		]
		[builders.vmware-iso.arrays]
			vboxmanage = [
				"cpus=1",
				"memory=1024"	
			]
post_processor_types = [
	"vagrant"
]
[post_processors]
	[post_processors.vagrant]
		settings = [
			"compression_level = 9",
			"keep_input_artifact = false",
			"output =  :build_name.box"
		]
provisioner_types = [
	"shell"
]
[provisioners]
	[provisioners.shell]
		settings = [
			"execute_command = execute.command"
		]
		[provisioners.shell.arrays]
			scripts = [ 
				"setup.sh",
				"vagrant.sh",
				"sudoers.sh",
				"cleanup.sh",
			]
