[1404-dev]
	distro = "ubuntu"
	description = "ubuntu LTS 1404 amd64 vagrant build"
	arch = "amd64"
	image = "server"
	release = "14.04"
	builder_types = [
		"virtualbox-iso"
	]
	[1404-dev.builders]
		[1404-dev.builders.common]
			settings = [
				"ssh_wait_timeout = 30m"
			]
		[1404-dev.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"memory=4096"
			]
	[1404-dev.provisioners]
		[1404-dev.provisioners.shell]
			[1404-dev.provisioners.shell.arrays]
				scripts = [ 
					"vagrant.sh",
					"sudoers.sh",
					"setup.sh",
					"desktop.sh",
					"browsers.sh",
					"editors.sh",
					"dev.sh",
					"go.sh",
					"cleanup.sh",
				]
