# This file contains the supported OS images, and the default build config for 
# each supported distribution, distro.
#
# To add another supported distribution, distro, the information about the 
# supported distribution releases, architectures, and images, along with any 
# distro specific settings must be added to this file in addition to adding
# the code to support the distro.

[distro]

	[distro.ubuntu]
		base_url = "http://releases.ubuntu.com"
		description = "Default template config and Rancher options for Ubuntu"
        	arch = [
        		"i386",
        		"amd64"
        	]
        	image = [
        		"server"
        	]
        	release = [
        		"10.04",
        		"12.04",
			"12.10",
			"13.04",
        		"13.10",
			"14.04"
        	]
        	default_image = [
        		"release = 12.04",
        		"image = server",
        		"arch = amd64",
        	]
	
	[distro.centos]
		base_url = ""
		description = "Default template config and Rancher options for CentOS"
		arch = [
		        "i386",
		        "x86_64"
		]
		image = [
		        "minimal",
		        "netinstall"
		]
		release = [
		        "5",
	        	"6"
		]
		default_image = [
		    	"release = 6",
		    	"image = minimal",
		    	"arch = x86_64",
		]

