# This file contains the supported OS images, and the default build config for 
# each supported distribution, distro.
#
# To add another supported distribution, distro, the information about the 
# supported distribution releases, architectures, and images, along with any 
# distro specific settings must be added to this file in addition to adding
# the code to support the distro.

[distro]
	[distro.ubuntu]
	base_url = "http://releases.ubuntu.com/"
	description = "Default template config and Rancher options for Ubuntu"
       	arch = [
       		"i386",
       		"amd64"
       	]
       	image = [
       		"server"
       	]
       	release = [
       		"10.04",
       		"12.04",
		"12.10",
		"13.04",
       		"13.10",
		"14.04"
       	]
       	default_image = [
       		"release = 12.04",
       		"image = server",
       		"arch = amd64",
       	]
	builder_types = [
		"virtualbox-iso"
	]
	post_processor_types = [
		"vagrant",
		"vagrant-cloud"
	]
	provisioner_types = [
		"shell",
		"file"
	]
		[distro.ubuntu.builders]
			[distro.ubuntu.builders.common]
			settings = [
				"boot_wait = 15s",
				"headless = false"
			]
			[distro.ubuntu.builders.virtualbox-iso]
				[distro.ubuntu.builders.virtualbox-iso.arrays]
				vm_settings = [
					"memory=2048"
				]
		[distro.ubuntu.post_processors]
			[distro.ubuntu.post_processors.vagrant]
				[distro.ubuntu.post_processors.vagrant.arrays]
				only = [
					"virtualbox-iso",
					"virtualbox-ovf"
				]
			[distro.ubuntu.post_processors.vagrant-cloud]
			settings = [
				"access_token = youAccessContentNotInAGitRepo",
				"box_tag = vagrantCloudAccout/boxTag",
				"version = 0.0.1"
			]
				[distro.ubuntu.post_processors.vagrant-cloud.arrays]
				only = [
					"virtualbox-iso",
					"virtualbox-ovf"
				]

		[distro.ubuntu.provisioners]
			[distro.ubuntu.provisioners.vagrant]
				[distro.ubuntu.provisioners.vagrant.arrays]
				only = [
					"virtualbox-iso",
					"virtualbox-ovf"
				]				
			[distro.ubuntu.provisioners.file]
				settings = [
					"source = source/dir",
					"destination = destination/dir"
				]

	
	[distro.centos]
	base_url = ""
	description = "Default template config and Rancher options for CentOS"
	arch = [
	        "i386",
	        "x86_64"
	]
	image = [
	        "minimal",
	        "netinstall"
	]
	release = [
	        "5",
        	"6"
	]
	default_image = [
	    	"release = 6",
	    	"image = minimal",
	    	"arch = x86_64",
	]

