# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[build] 
	[build.1204-amd64-server]
		distro = "ubuntu"
		description = "ubuntu LTS 1204 amd64 server build, minimal install"
		arch = "amd64"
		image = "server"
		release = "12.04"
		builder_types = [
			"virtualbox-iso"
		]
		[build.1204-amd64-server.builders]
			[build.1204-amd64-server.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.1204-amd64-server.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"--memory=4096"
			]
	[build.1404-amd64-salt]
		distro = "ubuntu"
		description = "ubuntu LTS 1404 amd64 server build, minimal salt install"
		arch = "amd64"
		image = "server"
		release = "14.04"
		builder_types = [
			"virtualbox-iso"
		]
		provisioner_types = [
			"shell",
			"salt-masterless"
		]
		[build.1404-amd64-salt.builders]
			[build.1404-amd64-salt.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.1404-amd64-salt.builders.virtualbox-iso.arrays]
			vboxmanage = [
				"--memory=4096"
			]
		[build.1404-amd64-salt.provisioners]
			[build.1404-amd64-salt.provisioners.salt-masterless]
			settings = [
				"local_state_tree = ~/code/saltstack/saltbase/salt"
			]
		
	[build.1404-dev]
		distro = "ubuntu"
		description = "ubuntu LTS 1404 amd64 desktop build, minimal install w stuff for development"
	        arch = "amd64"
	        release = "14.04"
	        image = "server"
	        builder_types = [
				"virtualbox-iso"
			]
		post_processor_types = [
			"vagrant"
		]
		provisioner_types = [
			"shell"
		]
		[build.1404-dev.builders]
				[build.1404-dev.builders.virtualbox-iso.arrays]
				vboxmanage = [
					"--memory=4096"
				]

		[build.1404-dev.post_processors]
			[build.1404-dev.post_processors.vagrant]
				[build.1404-dev.post_processors.vagrant.arrays]
				only = [
					"virtualbox-iso"
				]
		[build.1404-dev.provisioners]
			[build.1404-dev.provisioners.shell]
				[build.1404-dev.provisioners.shell.arrays]
				only = [
					"virtualbox-iso"
				]
				scripts = [ 
					":scripts_dir/setup.sh",
					":scripts_dir/sudoers.sh",
					":scripts_dir/vagrant.sh",
					":scripts_dir/dev_stuff.sh",					
					":scripts_dir/customize.sh",
					":scripts_dir/cleanup.sh",
				]

	[build.1404-go]
		distro = "ubuntu"
		description = "ubuntu LTS 1404 amd64 desktop build, minimal install w go"
	        arch = "amd64"
	        release = "14.04"
	        image = "desktop"
	        builder_types = [
				"virtualbox-iso"
			]
		post_processor_types = [
			"vagrant"
		]
		provisioner_types = [
			"shell"
		]
		[build.1404-go.builders]
				[build.1404-go.builders.virtualbox-iso.arrays]
				vboxmanage = [
					"--memory=4096"
				]

		[build.1404-go.post_processors]
			[build.1404-go.post_processors.vagrant]
				[build.1404-go.post_processors.vagrant.arrays]
				only = [
					"virtualbox-iso"
				]
		[build.1404-go.provisioners]
			[build.1404-go.provisioners.shell]
				[build.1404-go.provisioners.shell.arrays]
				only = [
					"virtualbox-iso"
				]
				scripts = [ 
					":scripts_dir/setup.sh",
					":scripts_dir/sudoers.sh",
					":scripts_dir/vagrant.sh",
					":scripts_dir/customize.sh",
					":scripts_dir/go.sh",
					":scripts_dir/cleanup.sh",
				]

	[build.1404-chef]
		distro = "ubuntu"
		description = "ubuntu LTS 1404 amd64 desktop build, minimal install w chef"
	        arch = "amd64"
	        release = "14.04"
	        image = "server"
	        builder_types = [
				"virtualbox-iso"
			]
		post_processor_types = [
			"vagrant"
		]
		provisioner_types = [
			"chef-solo"
		]
		[build.1404-chef.builders]
				[build.1404-chef.builders.virtualbox-iso.arrays]
				vboxmanage = [
					"--memory=4096"
				]

		[build.1404-chef.post_processors]
			[build.1404-chef.post_processors.vagrant]
				[build.1404-chef.post_processors.vagrant.arrays]
				only = [
					"virtualbox-iso"
				]
		[build.1404-chef.provisioners]
			[build.1404-chef.provisioners.chef-solo]
				[build.1404-chef.provisioners.chef-solo.arrays]
				only = [
					"virtualbox-iso"
				]
				cookbook_paths = [ 
					":src_dir/cookbooks",
				]

        [build.centos6]
		distro = "centos"
		description = "Centos 6 w virtualbox-iso only"
		builder_types = [
			"virtualbox-iso"
		]

        [build.centos6-salt]
		distro = "centos"
		description = "Centos 6 with salt provisioning"
		builder_types = [
			"virtualbox-iso"
		]
		provisioner_types = [
			"salt-masterless"
		]
		[build.centos6-salt.provisioner.salt-masterless]
			settings = [
				"local_state_tree = ~/saltstack/centos6/salt"
			]
			

	[build.centos6-ansible]
		distro = "centos"
		description = "Centos6 with ansible provisioning"
		builder_types = [
			"virtualbox-iso"
		]
		provisioner_types = [
			"ansible-local"
		]
		[build.centos6-ansible.provisioner.ansible-local]
			settings = [
				"command = ansible-playbook-command-override",
				"inventory_file = playbook-inventory.yaml",
				"playbook_file = local.yaml"
			]

	[build.centos6-chef-solo]
		distro = "centos"
		description = "CentOS6 with chef-solo provisioning"
		builder_types = [
			"virtualbox-iso"
		]
		provisioner_types = [
			"chef-solo"
		]
		[build.centos6-chef-solo.provisioner.chef-solo]
			[build.centos6-chef-solo.provisioner.chef-solo.arrays]
				cookbook_paths = [
					"cookbooks"
				]
				remote_cookbook_paths= [
					"remote_cookbooks"
				]
				run_list = [
					"runlist"
				]
				settings = [
					"config_template = chef.config.tpl",
					"data_bags_path = data.bags.path",
					"encrypted_data_bag_secret_path = encrypted.data.bag.secret.path",
					"execute_command = :command_src_dir/:buildname/chef/execute.command",
					"install_command = :command_src_dir/:buildname/chef/install.command",
					"json = :src_dir/:buildname/chef/node_attributes.json",
					"prevent_sudo = false",
					"roles_path = :src_dir/:buildname/roles",
					"skip_install = false",
					"staging_directory = :out_dir/staging/"
				]
				
	[build.wheezy-salt]
		distro = "debian"
		description = "debian wheezy w saltstack"
	        arch = "amd64"
	        builder_types = [
				"virtualbox-iso"
			]
		post_processor_types = [
			"vagrant"
		]
		provisioner_types = [
			"shell"
		]
		[build.wheezy-salt.builders]
				[build.wheezy-salt.builders.virtualbox-iso.arrays]
				vboxmanage = [
					"--memory=4096"
				]
		[build.wheezy-salt.provisioners]
			[build.wheezy-salt.provisioners.shell]
				[build.wheezy-salt.provisioners.shell.arrays]
					scripts = [ 
						":scripts_dir/setup.sh",
						":scripts_dir/sudoers.sh",
						":scripts_dir/vagrant.sh",
						":scripts_dir/dev_stuff.sh",
						":scripts_dir/customize.sh",
						":scripts_dir/install_salt.sh",
						":scripts_dir/cleanup.sh",
					]				