# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[build] 
	[build.1204-amd64-server]
		type = "ubuntu"
		description = "ubuntu LTS 1204 amd64 server build, minimal install"
		arch = "amd64"
		image = "server"
		release = "12.04"
		builder_type = [
			"virtualbox-iso"
		]
		[build.1204-amd64-server.builders]
			[build.1204-amd64-server.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.1204-amd64-server.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]

	[build.1404-dev]
		type = "ubuntu"
		description = "ubuntu LTS 1404 amd64 desktop build, minimal install w go"
	        arch = "amd64"
	        release = "14.04"
	        image = "server"
	        builder_type = [
			"virtualbox-iso"
		]
		[build.1404-dev.builders]
			[build.1404-dev.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]
		[build.1404-dev.post-processors]
			[build.1404-dev.post-processors.vagrant]
			except = [
				"docker"
			]
			only = [
				"virtualbox-iso"
			]
		[build.1404-dev.provisioners]
			[build.1404-dev.provisioners.shell]
			except = [
				"docker"
			]
			only = [
				"virtualbox-iso"
			]
