# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[build] 
	[build.1204-amd64-server]
		distro = "ubuntu"
		description = "ubuntu LTS 1204 amd64 server build, minimal install"
		arch = "amd64"
		image = "server"
		release = "12.04"
		builder_types = [
			"virtualbox"
		]
		[build.1204-amd64-server.builders]
			[build.1204-amd64-server.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.1204-amd64-server.builders.virtualbox.arrays]
			vm_settings = [
				"memory=4096"
			]

	[build.1404-dev]
		distro = "ubuntu"
		description = "ubuntu LTS 1404 amd64 desktop build, minimal install w go"
	        arch = "amd64"
	        release = "14.04"
	        image = "server"
	        builder_types = [
			"virtualbox"
		]
		post_processor_types = [
			"vagrant"
		]
		provisioner_types = [
			"shell-scripts"
		]
		[build.1404-dev.builders]
				[build.1404-dev.builders.virtualbox.arrays]
				vm_settings = [
					"memory=4096"
				]

		[build.1404-dev.post_processors]
			[build.1404-dev.post_processors.vagrant]
				[build.1404-dev.post_processors.vagrant.arrays]
				except = [
					"docker"
				]
				only = [
					"virtualbox"
				]
		[build.1404-dev.provisioners]
			[build.1404-dev.provisioners.shell-scripts]
				[build.1404-dev.provisioners.shell-scripts.arrays]
				except = [
					"docker"
				]
				only = [
					"virtualbox"
				]
				scripts = [ 
					":scripts_dir/setup.sh",
					":scripts_dir/sudoers.sh",
					":scripts_dir/vagrant.sh",
					":scripts_dir/dev_stuff.sh",
					":scripts_dir/customize.sh",
					":scripts_dir/cleanup.sh",
				]


        [build.centos6]
		distro = "centos"
		description = "Centos 6 w virtualbox only"
		builder_types = [
			"virtualbox"
		]

        [build.centos6-salt]
		distro = "centos"
		description = "Centos 6 with salt provisioning"
		builder_types = [
			"virtualbox"
		]
		provisioner_types = [
			"salt"
		]
		[build.centos6-salt.provisioner.salt]
			settings = [
				"local_state_tree = ~/saltstack/centos6/salt"
			]
			

	[build.centos6-ansible]
		distro = "centos"
		description = "Centos6 with ansible provisioning"
		builder_types = [
			"virtualbox"
		]
		provisioner_types = [
			"ansible"
		]
		[build.centos6-ansible.provisioner.ansible]
			settings = [
				"command = ansible-playbook-command-override",
				"inventory_file = playbook-inventory.yaml",
				"playbook_file = local.yaml"
			]
			[build.centos6-ansible.provisioner.ansible.arrays]
			extra_arguments = [
				"arg1",
				"arg2"
			]

	[build.centos6-chef-solo]
		distro = "centos"
		description = "CentOS6 with chef-solo provisioning"
		builder_types = [
			"virtualbox"
		]
		provisioner_types = [
			"chef-solo"
		]
		[build.centos6-chef-solo.provisioner.chef-solo]
			[build.centos6-chef-solo.provisioner.chef-solo.arrays]
				cookbook_paths = [
					"cookbooks"
				]
				remote_cookbook_paths= [
					"remote_cookbooks"
				]
				run_list = [
					"runlist"
				]
				settings = [
					"config_template = chef.config.tpl",
					"data_bags_path = data.bags.path",
					"encrypted_data_bag_secret_path = encrypted.data.bag.secret.path",
					"execute_command = :command_src_dir/:buildname/chef/execute.command",
					"install_command = :command_src_dir/:buildname/chef/install.command",
					"json = :src_dir/:buildname/chef/node_attributes.json",
					"prevent_sudo = false",
					"roles_path = :src_dir/:buildname/roles",
					"skip_install = false",
					"staging_directory = :out_dir/staging/"
				]

