# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[build] 
	[build.1204-amd64-server]
		type = "ubuntu"		# id is the distro ID, this is used to find default settings.
		description = "ubuntu LTS 1204 amd64 server build, minimal install"
		arch = "amd64"
		image = "server"
		release = "1204"
		builder_type = [
			"virtualbox-iso"
		]
		[build.1204-amd64-server.builders]
			[build.1204-amd64-server.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.1204-amd64-server.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]

	[build.1310-amd64-desktop]
		type = "ubuntu"		# id is the distro ID, this is used to find default settings.
		description = "ubuntu 1310 amd64 desktop build, minimal install"
	        arch = "amd64"
	        release = "1310"
	        image = "desktop"
	        builder_type = [
			"virtualbox-iso"
		]
