# This file contains the supported OS images, and the default build config for 
# each supported distribution, distro.
#
# To add another supported distribution, distro, the information about the 
# supported distribution releases, architectures, and images, along with any 
# distro specific settings must be added to this file in addition to adding
# the code to support the distro.
[centos]
base_url = ""
description = "Default template config and Rancher options for CentOS"
arch = [
	"i386",
	"x86_64"
]
image = [
	"Minimal"
]
release = [
	"6",
	"7"
]
default_image = [
	"release = 7",
	"image = Minimal",
	"arch = x86_64"
]
[debian]
base_url = "http://cdimage.debian.org/debian-cd/"
description = "Default template config and Rancher options for Debian"
arch = [
	"i386",
	"amd64"
]
image = [
	"netinst"
]
release = [
	"8"
]
default_image = [
	"release = 8",
	"image = netinst",
	"arch = amd64"
]
[ubuntu]
base_url = "http://releases.ubuntu.com/"
description = "Default template config and Rancher options for Ubuntu"
arch = [
	"i386",
	"amd64"
]
image = [
	"server"
]
release = [
	"12.04",
	"14.04",
	"14.10",
	"15.04",
	"15.10"
]
default_image = [
	"release = 15.04",
	"image = server",
	"arch = amd64"
]
