# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[build] 
	[build.test1]
		type = "ubuntu"		# id is the distro ID, this is used to find default settings.
		description = "Test build template"
		arch = "amd64"
		image = "server"
		release = "1204"
		builder_type = [
			"virtualbox-iso"
		]
		[build.test1.builders]
			[build.test1.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.test1.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]
		[build.test1.post_processors]
			[build.test1.post_processors.vagrant]
			settings = [
				"output = out_dir/packer.box"
			]
		[build.test1.provisioners]
			[build.test1.provisioners.shell]
			settings = [
				"execute_command = execute.command"
			]
			scripts = [
				":scripts_dir/ubuntu/setup.sh",
				":scripts_dir/ubuntu/vagrant.sh",
				":scripts_dir/ubuntu/cleanup.sh"
			]
