# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[build] 
	[build.test1]
		type = "ubuntu"
		description = "Test build template #1"
		arch = "amd64"
		image = "server"
		release = "1204"
		builder_type = [
			"virtualbox-iso"
		]
		[build.test1.builders]
			[build.test1.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.test1.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]
		[build.test1.post_processors]
			[build.test1.post_processors.vagrant]
			settings = [
				"output = :out_dir/packer.box"
			]
			only = ["virtualbox-iso"]
			except = ["docker"]
		[build.test1.provisioners]
			[build.test1.provisioners.shell]
			settings = [
				"execute_command = :commands_src_dir/execute_test.command"
			]
			only = ["virtualbox-iso"]
			except = ["docker"]
			scripts = [
				":scripts_dir/setup_test.sh",
				":scripts_dir/vagrant_test.sh",
				":scripts_dir/cleanup_test.sh"
			]

	[build.test2]
		type = "ubuntuu"
		description = "Test build template #2: causes an error"
		arch = "amd64"
		image = "desktop"
		release = "1204"
		builder_type = [
			"virtualbox-iso",
			"vmware-iso"
		]
		[build.test2.builders]
			[build.test2.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.test2.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]

