# Builds are named configurations that specify the distro to use, at minimum, and 
# define the final overrides and settings for generating a Packer Template. The 
# generated Packer template will be the result of merging the settings within the
# build configuration with the Rancher and distro defaults.
[build] 
	[build.test1]
		type = "ubuntu"
		description = "Test build template #1"
		arch = "amd64"
		image = "server"
		release = "1204"
		builder_type = [
			"virtualbox-iso"
		]
		[build.test1.builders]
			[build.test1.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.test1.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]
		post_processor_types = [
			"vagrant",
			"vagrant-cloud"
		]
		[build.test1.post_processors]
			[build.test1.post_processors.vagrant]
			settings = [
				"output = :out_dir/packer.box"
			]
				[build.test1.post_processors.vagrant.arrays]
					except = ["docker"]
					only = ["virtualbox-iso"]

			[build.test1.post_processors.vagrant-cloud]
			settings = [
				"access_token = getAValidTokenFrom-VagrantCloud.com",
				"box_tag = foo/bar/baz",
				"no_release = false",
				"version = 1.0.2"
			]
		provisioner_types = [
			"shell"
		]
		[build.test1.provisioners]
			[build.test1.provisioners.shell]
			settings = [
				"execute_command = :commands_src_dir/execute_test.command"
			]
				[build.test1.provisioners.shell.arrays]
				except = ["docker"]
				only = ["virtualbox-iso"]
				scripts = [
					":scripts_dir/setup_test.sh",
					":scripts_dir/vagrant_test.sh",
					":scripts_dir/cleanup_test.sh"
				]
	[build.test2]
		type = "ubuntuu"
		description = "Test build template #2: causes an error"
		arch = "amd64"
		image = "desktop"
		release = "1204"
		builder_type = [
			"virtualbox-iso",
			"vmware-iso"
		]
		[build.test2.builders]
			[build.test2.builders.common]
			settings = [
				"ssh_wait_timeout = 300m"
			]
			[build.test2.builders.virtualbox-iso]
			vm_settings = [
				"memory=4096"
			]

        [build.test-centos6-salt]
		type = "centos"
		description = "Test build template for salt provisioner using CentOS6"
		builder_type = [
			"virtualbox-iso"
		]
		provisioner_type = [
			"shell",
			"salt-masterless"
		]
		[build.centos6-salt.provisioner]
			[build.centos6-salt.provisioner.salt-masterless]
				settings = [
					"local_state_tree = ~/saltstates/centos6/salt",
					"skip_bootstrap = true"
				]
