# default builder variable settings for Rancher
# 
# Some of the values in here are not intended to be used as is. These are
# overridden at the distro level, at minimum, e.g. supported.toml. Anything
# set in subsequent configuration files, along with what may be passed on the
# command-line, will override anything set here.
#
# Type corresponds with a Packer Builder's `type` variable. This is typically
# the distro name.
description = "Test Default Rancher template"
name = ":type-:release-:image-:arch"
commands_src_dir = ":src_dir/commands"
http_dir = "http"
http_src_dir = ":src_dir/http"
out_dir = "../test_files/out/:type"
scripts_dir = "scripts"
scripts_src_dir = ":src_dir/scripts"
src_dir = "../test_files/src/:type"
min_packer_version = "0.4.0"
builder_type = [
    "virtualbox-iso",
    "vmware-iso"
]
[builders]
	[builders.common]
		settings = [	
			"boot_command = :commands_src_dir/boot_test.command",
			"boot_wait = 5s",
			"disk_size = 20000",
			"http_directory = http",
			"iso_checksum_type = sha256",
			"shutdown_command = :commands_src_dir/shutdown_test.command",
			"ssh_password = vagrant",
			"ssh_port = 22",
			"ssh_username = vagrant",
			"ssh_wait_timeout = 240m"
		]
	[builders.virtualbox-iso]
		vm_settings = [
			"cpus=1",
			"memory=1024"	
		]
	[builders.vmware-iso]
		vm_settings = [
			"cpuid.coresPerSocket=1",
			"memsize=1024",
			"numvcpus=1"
		]
[post_processors]
	[post_processors.vagrant]
		settings = [
			"keep_input_artifact = false",
			"output = out/rancher-packer.box"
		]
[provisioners]
	[provisioners.shell]
		settings = [
			"execute_command = :commands_src_dir/execute_test.command"
		]
		scripts = [ 
			":scripts_dir/setup_test.sh",
			":scripts_dir/base_test.sh",
			":scripts_dir/vagrant_test.sh",
			":scripts_dir/cleanup_test.sh",
			":scripts_dir/zerodisk_test.sh"
		]
