# Default builder variable settings for Rancher. Merging the contents of this
# file with supported.toml provids the default settings for each distro.
description = "Test Default Rancher template"
name = ":build_name"
#command_dir = "commands"
template_output_dir = "packer_templates/:build_name"
template_output_dir_is_relative = true
packer_output_dir = "packer_boxes/:build_name"
source_dir = "src"
source_dir_is_relative = true
min_packer_version = "0.4.0"
include_component_string = true
builder_ids = [
    "virtualbox-iso",
]
post_processor_ids = [
	"vagrant"
]
provisioner_ids = [
	"shell"
]
[builders]
	[builders.common]
		settings = [	
			"boot_command = boot_test.command",
			"boot_wait = 5s",
			"disk_size = 20000",
			"guest_os_type = ",
			"headless = true",
			"http_directory = http",
			"iso_checksum_type = sha256",
			"output_directory = :packer_output_dir",		
			"shutdown_command = shutdown_test.command",
			"ssh_password = vagrant",
			"ssh_port = 22",
			"ssh_username = vagrant",
			"ssh_wait_timeout = 240m",
		]
	[builders.virtualbox-iso]
		settings = [
			"guest_additions_path = VBoxGuestAdditions_{{ .Version }}.iso",
			"virtualbox_version_file = .vbox_version"
		]
		[builders.virtualbox-iso.arrays]
			vboxmanage = [
				"cpus=1",
				"memory=1024"	
			]
[post_processors]
	[post_processors.vagrant]
		settings = [
			"compression_level = 9",
			"keep_input_artifact = false",
			"output = :build_name.box"
		]
[provisioners]
	[provisioners.shell]
		settings = [
			"execute_command = execute_test.command"
		]
		[provisioners.shell.arrays]
			scripts = [ 
				"setup_test.sh",
				"vagrant_test.sh",
				"sudoers_test.sh",
				"cleanup_test.sh",
			]
