# Default builder variable settings for Rancher. Merging the contents of this
# file with supported.toml provids the default settings for each distro.
description = "Test Default Rancher template"
name = ":build_name"
commands_src_dir = ":src_dir/commands"
http_dir = "http"
http_src_dir = ":src_dir/http"
out_dir = "../test_files/out/:distro/:build_name"
scripts_dir = "scripts"
scripts_src_dir = ":src_dir/scripts"
src_dir = "../test_files/src/:distro"
min_packer_version = "0.4.0"
builder_types = [
    "virtualbox-iso",
    "vmware-iso"
]
post_processor_types = [
	"vagrant",
	"vagrant-cloud"
]
provisioner_types = [
	"shell-scripts"
]
[builders]
	[builders.common]
	settings = [	
		"boot_command = :commands_src_dir/boot_test.command",
		"boot_wait = 5s",
		"disk_size = 20000",
		"guest_os_type = ",
		"headless = true",
		"http_directory = http",
		"iso_checksum_type = sha256",
		"shutdown_command = :commands_src_dir/shutdown_test.command",
		"ssh_password = vagrant",
		"ssh_port = 22",
		"ssh_username = vagrant",
		"ssh_wait_timeout = 240m"
	]
	[builders.virtualbox-iso]
	settings = [
		"virtualbox_version_file = .vbox_version"
	]
		[builders.virtualbox-iso.arrays]
			vm_settings = [
				"cpus=1",
				"memory=1024"	
			]
	[builders.vmware-iso]
		[builders.vmware-iso.arrays]
			vm_settings = [
				"cpuid.coresPerSocket=1",
				"memsize=1024",
				"numvcpus=1"
			]
[post_processors]
	[post_processors.vagrant]
		settings = [
			"compression_level = 9",
			"keep_input_artifact = false",
			"output = out/rancher-packer.box"
		]
		[post_processors.vagrant.arrays]
			only = [
				"virtualbox-iso"
			]		
			
	[post_processors.vagrant-cloud]
		settings = [
			"access_token = getAValidTokenFrom-VagrantCloud.com",
			"box_tag = foo/bar",
			"no_release = true",
			"version = 1.0.1"
		]
[provisioners]
	[provisioners.shell-scripts]
		settings = [
			"execute_command = :commands_src_dir/execute_test.command"
		]
		[provisioners.shell-scripts.arrays]
			except = [
				"docker"
			]
			only = [
				"virtualbox-iso"
			]
			scripts = [ 
				":scripts_dir/setup_test.sh",
				":scripts_dir/vagrant_test.sh",
				":scripts_dir/sudoers_test.sh",
				":scripts_dir/cleanup_test.sh",
			]
