# This file contains the supported OS images, and the default build config for 
# each supported distribution, distro.
#
# To add another supported distribution, distro, the information about the 
# supported distribution releases, architectures, and images, along with any 
# distro specific settings must be added to this file in addition to adding
# the code to support the distro.

[distro]

	[distro.ubuntu]
	base_url = "http://releases.ubuntu.com/"
	description = "Test supported distribution template"
       	arch = [
       		"i386",
       		"amd64"
       	]
       	image = [
       		"desktop",
       		"server",
       		"alternate"
       	]
       	release = [
       		"10.04",
       		"12.04",
       		"12.10",
       		"13.04",
       		"13.10"
       	]
       	default_image = [
       		"release = 12.04",
       		"image = server",
       		"arch = amd64",
       	]
	[distro.ubuntu.builders]			
		[distro.ubuntu.builders.common]
		settings = [
		    	"boot_command = :commands_src_dir/boot_test.command",
	    		"shutdown_command = :commands_src_dir/shutdown_test.command"
		]
		[distro.ubuntu.builders.virtualbox-iso]
		vm_settings = [
			"memory=2048"
		]
		[distro.ubuntu.builders.vmware-iso]
		vm_settings = [
			"memsize=2048"
		]
	[distro.ubuntu.post_processors]
		[distro.ubuntu.post_processors.vagrant]
		settings = [
			"output = out/:type-:arch-:version-:image-packer.box"
		]
		[distro.ubuntu.provisioners]
			[distro.ubuntu.provisioners.shell]
			settings = [
				"execute_command = :commands_src_dir/execute_test.command"
			]
			scripts = [ 
				"scripts/setup_test.sh",
				"scripts/base_test.sh",
				"scripts/vagrant_test.sh",
				"scripts/cleanup_test.sh",
				"scripts/zerodisk_test.sh"
			]

	[distro.centos]
	base_url = "http://mirrorlist.centos.org/?release=%s&arch=&s&repo=os"
	description = "Test template config and Rancher options for CentOS"
	out_dir = "out/centos"
	src_dir = "src/centos"
	arch = [
	        "i386",
	        "x86_64"
	]
	image = [
	        "minimal",
	        "netinstall"
	]
	release = [
	        "5",
        	"6"
	]
	default_image = [
	    	"release = 6",
	    	"image = minimal",
	    	"arch = x86_64",
	]
