# supported_no_base_url_test.toml contains a supported distro definition for
# Ubuntu w/o a base_url, which should cause an error.
#
# Each distribution has its own base_url rules. In contrast to Ubuntu, the
# base_url field for CentOS can be left empty as its only used to override
# the iso_image url, instead of having it come from a randomly selected
# mirror on CentOS's mirror list. 
#
# To test, only add distributions which need base_url validation in here.
# and use accordinly from test.

[distro]

	[distro.ubuntu]
	base_url = ""
	description = "Test supported distribution template"
       	arch = [
       		"i386",
       		"amd64"
       	]
       	image = [
       		"desktop",
       		"server",
       		"alternate"
       	]
       	release = [
       		"10.04",
       		"12.04",
       		"12.10",
       		"13.04",
       		"13.10"
       	]
       	default_image = [
       		"release = 12.04",
       		"image = server",
       		"arch = amd64",
       	]
	[distro.ubuntu.builders]			
		[distro.ubuntu.builders.common]
			settings = [
			    	"boot_command = ../test_files/src/ubuntu/commands/boot_test.command",
	 		   		"shutdown_command = :command_src_dir/shutdown_test.command"
			]
		[distro.ubuntu.builders.virtualbox-iso]
			[distro.ubuntu.builders.virtualbox-iso.arrays]
				vm_settings = [
					"memory=2048"
				]
		[distro.ubuntu.builders.vmware-iso]
			[distro.ubuntu.builders.vmware-iso.arrays]
				vm_settings = [
					"memsize=2048"
				]
	[distro.ubuntu.post_processors]
		[distro.ubuntu.post_processors.vagrant]
			settings = [
				"output = out/:build_name-packer.box"
			]
		[distro.ubuntu.provisioners]
			[distro.ubuntu.provisioners.shell-scripts]
				settings = [
					"execute_command = :command_src_dir/execute_test.command"
				]
			[distro.ubuntu.provisioners.shell-scripts.arrays]
				scripts = [ 
					":scripts_dir/setup_test.sh",
					":scripts_dir/base_test.sh",
					":scripts_dir/vagrant_test.sh",
					":scripts_dir/sudoers_test.sh",
					":scripts_dir/cleanup_test.sh"
				]
